# Generated by Django 4.1.1 on 2022-09-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='folder/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image with text',
                'verbose_name_plural': 'Images with text',
            },
        ),
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Text',
            },
        ),
    ]
