# Generated by Django 4.1.1 on 2022-09-23 08:22

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Page blocks')),
            ],
        ),
    ]
